# Generated by Django 4.0.3 on 2022-03-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0002_remove_prayer_prayer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayer',
            name='prayer_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
